version: '3.3'
services:
  slack-jenkins-bot:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: slack-jenkins-bot
    command: "npm run prod"
    ports:
      - 80:80
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: bot
      MYSQL_DATABASE: bot
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
