version: '3.3'
services:
  app:
    image: ghcr.io/bsramin/slack-jenkins-bot/app:1.1.0
    env_file: .env
    command: "npm run prod"
    ports:
      - ${DOCKER_EXPOSE_HTTP_PORT}:80
  db:
    image: mysql:5.7
    restart: always
    ports:
      - ${DOCKER_EXPOSE_MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: bot
      MYSQL_DATABASE: slack_jenkins_bot
    volumes:
      - mysql-data:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  mysql-data:
